<?php

// namespace Database\Seeders;

use App\Models\OficinaDocumento;
use Illuminate\Database\Seeder;

class OficinaDocumentoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>2,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>2,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>2,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>3,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>3,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>3,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>4,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>4,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>4,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>5,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>5,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>5,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>6,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>6,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>6,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>7,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>7,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>7,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>8,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>8,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>8,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>9,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>9,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>9,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>10,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>10,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>10,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>11,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>11,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>11,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>12,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>12,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>12,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>13,
            "clase_documento_id"=>1,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>13,
            "clase_documento_id"=>2,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>13,
            "clase_documento_id"=>3,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>14,
            "clase_documento_id"=>4,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>14,
            "clase_documento_id"=>5,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>14,
            "clase_documento_id"=>6,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>14,
            "clase_documento_id"=>7,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>14,
            "clase_documento_id"=>8,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>14,
            "clase_documento_id"=>9,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>14,
            "clase_documento_id"=>10,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>15,
            "clase_documento_id"=>11,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>16,
            "clase_documento_id"=>12,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>17,
            "clase_documento_id"=>13,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>18,
            "clase_documento_id"=>14,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>19,
            "clase_documento_id"=>15,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>19,
            "clase_documento_id"=>16,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>20,
            "clase_documento_id"=>17,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>20,
            "clase_documento_id"=>18,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>20,
            "clase_documento_id"=>19,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>20,
            "clase_documento_id"=>20,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>21,
            "clase_documento_id"=>21,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>22,
            "clase_documento_id"=>22,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>23,
            "clase_documento_id"=>23,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>23,
            "clase_documento_id"=>24,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>23,
            "clase_documento_id"=>25,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>23,
            "clase_documento_id"=>26,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>23,
            "clase_documento_id"=>27,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>23,
            "clase_documento_id"=>28,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>23,
            "clase_documento_id"=>29,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>23,
            "clase_documento_id"=>30,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>24,
            "clase_documento_id"=>31,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>25,
            "clase_documento_id"=>32,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>25,
            "clase_documento_id"=>33,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>25,
            "clase_documento_id"=>34,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>26,
            "clase_documento_id"=>35,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>26,
            "clase_documento_id"=>36,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>26,
            "clase_documento_id"=>37,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>27,
            "clase_documento_id"=>38,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>27,
            "clase_documento_id"=>39,
        ]);
        //----------------------------------
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>28,
            "clase_documento_id"=>40,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>28,
            "clase_documento_id"=>41,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>28,
            "clase_documento_id"=>42,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>28,
            "clase_documento_id"=>43,
        ]);
        OficinaDocumento::firstOrcreate([
            "oficina_id"=>28,
            "clase_documento_id"=>44,
        ]);
    }
}
